<a href="https://colab.research.google.com/github/Rayyan52/Datasci-work/blob/main/Data_Science_Session_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy**


### **Creating array using NumPy**

In [ ]:
import numpy as np

In [ ]:
baithak1 = np.array([1,2,3,4,5])
baithak1

array([1, 2, 3, 4, 5])

In [ ]:
baithak1.dtype

dtype('int64')

In [ ]:
type(baithak1)

numpy.ndarray

NumPy Arrays using lists

In [ ]:
list =[1,2,3,4,5]
type(list)

list

In [ ]:
baithak = np.array(list)
type(baithak)

numpy.ndarray

NumPy Arrays?

1.   Matrices
2.   Vectors



In [ ]:
# matrix
# 1D , 2D , 3D
baithak2 = np.array([[[1,2,3,4,5],
                    [7,8,9,10,11],
                    [7,8,9,10,11]],

                    [[1,2,3,4,5],
                    [7,8,9,10,11],
                    [7,8,9,10,11]]])
baithak2


array([[[ 1,  2,  3,  4,  5],
        [ 7,  8,  9, 10, 11],
        [ 7,  8,  9, 10, 11]],

       [[ 1,  2,  3,  4,  5],
        [ 7,  8,  9, 10, 11],
        [ 7,  8,  9, 10, 11]]])

In [ ]:
# row vector
row_vector = np.array([[81,82,83,84],[1,2,5,6]])

row_vector

array([[81, 82, 83, 84],
       [ 1,  2,  5,  6]])

In [ ]:
# column vector
column_vector = np.array([[81],
                          [82],
                          [83]])

column_vector

array([[81],
       [82],
       [83]])

NumPy Arrays using built-in methods






In [ ]:
# arange
# zeros
# ones

# linspace - HW

array = np.arange(15)
array = np.arange(5,20) #(start, stop) (include, exclude)
array = np.arange(10,2,-1)
array

array([10,  9,  8,  7,  6,  5,  4,  3])

In [ ]:
zero = np.zeros(5)
zero

one = np.ones(5)
one


array([1., 1., 1., 1., 1.])

In [ ]:
arr =np.array([[1,2,3],[7,8,9]])

arr.reshape

In [ ]:
#reshapre
arr1 = np.arange(10,35)

Array with random numbers

In [ ]:
# HW np.random.rand

Array with random integers

In [ ]:
# HW np.random.randint

Maximum and Minimum

In [ ]:
print(arr1.max())
print(arr1.min())

34
10


Indexing

In [ ]:
baithak2 = np.array([[1,2,3,4,5],
                    [7,8,9,10,11],
                    [78,812,92,110,1]])

baithak2[:,1:]

array([[  2,   3,   4,   5],
       [  8,   9,  10,  11],
       [812,  92, 110,   1]])

Slicing


In [ ]:
baithak2[1:]

array([[  7,   8,   9,  10,  11],
       [ 78, 812,  92, 110,   1]])

In [ ]:
baithak2[1:,2]

array([ 9, 92])

In [ ]:
baithak2[1:,1:3]

array([[  8,   9],
       [812,  92]])

Join two arrays



#### Concatenate function

In [ ]:
arr1 = np.array([[1, 2, 3],[3,4,7]])

arr2 = np.array([[4, 5, 6],[5,8,1]])

arr = np.concatenate((arr2,arr1))

arr

array([[4, 5, 6],
       [5, 8, 1],
       [1, 2, 3],
       [3, 4, 7]])

#### Stack function

In [ ]:
arr1 = np.array([1,2,3])
arr2 = [4,5,6]
arr3 = [7,8,9]

In [ ]:
arr1.ndim

1

In [ ]:
arr3 = np.stack((arr1,arr2), axis=0)
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr3 = np.stack((arr1,arr2,arr3), axis=1)
arr3

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Split Into Arrays

In [ ]:
array_big = np.array([1,2,3,4,12,5,6,7,8,9,10,1,5,0,25,324,78,8])
len(array_big)

18

In [ ]:
new_arr =np.array_split(array_big,5)

In [ ]:
new_arr[2]

array([ 8,  9, 10,  1])

In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

new_arr2 = np.array_split(arr2d, 2, axis = 1)

new_arr2

[array([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11],
        [13, 14],
        [16, 17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

Search()

In [ ]:
array_big_10 = np.where(array_big >= 10)
array_big_10

(array([ 4, 10, 14, 15, 16]),)

In [ ]:
array_big_1 = np.where(array_big == 10)
array_big_1

(array([10]),)

Sort()

In [ ]:
array_big_sort = np.sort(array_big)[::-1]
array_big_sort

array([324,  78,  25,  12,  10,   9,   8,   8,   7,   6,   5,   5,   4,
         3,   2,   1,   1,   0])